import Sequelize, { Model } from 'sequelize';

class TriageRecord extends Model {
  static init(sequelize) {
    super.init(
      {
        id_patient: Sequelize.INTEGER,
        id_nurse: Sequelize.INTEGER,
        id_patient_record: Sequelize.INTEGER,
        manchesterPriority: Sequelize.INTEGER,
        mainComplain: Sequelize.STRING,
        nurseNotes: Sequelize.STRING,
        drugs: Sequelize.STRING,
        discriminators: Sequelize.STRING,
        hasAlergies: Sequelize.BOOLEAN,
        alergies: Sequelize.STRING,
        painRule: Sequelize.INTEGER,
        covid19: Sequelize.INTEGER,
        fc: Sequelize.FLOAT,
        fr: Sequelize.FLOAT,
        pas: Sequelize.FLOAT,
        pad: Sequelize.FLOAT,
        spo2: Sequelize.FLOAT,
        weight: Sequelize.FLOAT,
        headache: Sequelize.BOOLEAN,
        estadoMentalAlterado: Sequelize.BOOLEAN,
        estadoMentalAlteradoNotes: Sequelize.STRING,
        sinaisDeChoque_headache: Sequelize.BOOLEAN,
        sinaisDeChoqueNotes_headache: Sequelize.STRING,
        convulsion_headache: Sequelize.BOOLEAN,
        sinaisNeurologicosFocais_headache: Sequelize.BOOLEAN,
        sinaisNeurologicosFocaisNotes_headache: Sequelize.STRING,
        aumentoSubitoDaDor: Sequelize.BOOLEAN,
        aumentoSubitoDaDorNotes: Sequelize.STRING,
        perdaAgudaCompletaVisao: Sequelize.BOOLEAN,
        menigismo_headache: Sequelize.BOOLEAN,
        menigismoNotes_headache: Sequelize.STRING,
        pain_headache: Sequelize.INTEGER,
        temperature_headache: Sequelize.FLOAT,
        inconsciencia_headache: Sequelize.BOOLEAN,
        inconscienciaNotes_headache: Sequelize.STRING,
        diminuicaoVisao: Sequelize.BOOLEAN,
        nauseaEVomito: Sequelize.BOOLEAN,
        soreThroat: Sequelize.BOOLEAN,
        comprometimentoViasAereas_soathroat: Sequelize.BOOLEAN,
        comprometimentoViasAereasNotes_soathroat: Sequelize.STRING,
        pain_soathroat: Sequelize.INTEGER,
        estridorLaringeo: Sequelize.BOOLEAN,
        estridorLaringeoNotes: Sequelize.STRING,
        viagemRecente: Sequelize.BOOLEAN,
        temperatura_soathroat: Sequelize.FLOAT,
        dificuldadeDeglutir: Sequelize.BOOLEAN,
        ardenciaGarganta: Sequelize.BOOLEAN,
        convulsion: Sequelize.BOOLEAN,
        convulsaoAtiva: Sequelize.BOOLEAN,
        comprometimentoViasAereas_convulsion: Sequelize.BOOLEAN,
        comprometimentoViasAereasNotes_convulsion: Sequelize.STRING,
        alteracoesGlicemicas_convulsion: Sequelize.BOOLEAN,
        alteracoesGlicemicasNumber_convulsion: Sequelize.INTEGER,
        respiracaoInadequada: Sequelize.BOOLEAN,
        respiracaoInadequadaNotes: Sequelize.STRING,
        sinaisNeurologicosFocais_convulsion: Sequelize.BOOLEAN,
        sinaisNeurologicosFocaisNotes_convulsion: Sequelize.STRING,
        criseConvulsivaReentrante: Sequelize.BOOLEAN,
        menigismo_convulsion: Sequelize.BOOLEAN,
        menigismoNotes_convulsion: Sequelize.STRING,
        overdoseEnvenenamento: Sequelize.BOOLEAN,
        overdoseEnvenenamentoNotes: Sequelize.STRING,
        traumaCranianoRecente_convulsion: Sequelize.BOOLEAN,
        traumaCranianoRecenteNotes_convulsion: Sequelize.STRING,
        posComicial_convulsion: Sequelize.BOOLEAN,
        posComicialNotes_convulsion: Sequelize.STRING,
        epilepsiaTratada: Sequelize.BOOLEAN,
        epilepsiaTratadaNotes: Sequelize.STRING,
        criseConvulsivaRecente_convulsion: Sequelize.BOOLEAN,
        criseConvulsivaRecenteNotes_convulsion: Sequelize.STRING,
        fainting: Sequelize.BOOLEAN,
        alteracaoConsciencia_fainting: Sequelize.INTEGER,
        comprometimentoViasAereas_fainting: Sequelize.BOOLEAN,
        comprometimentoViasAereasNotes_fainting: Sequelize.STRING,
        alteracoesGlicemicas_fainting: Sequelize.BOOLEAN,
        alteracoesGlicemicasNumber_fainting: Sequelize.INTEGER,
        rigidez: Sequelize.STRING,
        rigidezNotes: Sequelize.BOOLEAN,
        sinaisDeChoque_fainting: Sequelize.BOOLEAN,
        sinaisDeChoqueNotes_fainting: Sequelize.STRING,
        pulsoAnormal: Sequelize.STRING,
        dorToracica: Sequelize.BOOLEAN,
        dorToracicaNotes: Sequelize.BOOLEAN,
        disturbioSubitoEquilibrio: Sequelize.BOOLEAN,
        disturbioSubitoEquilibrioNotes: Sequelize.STRING,
        pain_fainting: Sequelize.INTEGER,
        posComicial_fanting: Sequelize.BOOLEAN,
        posComicialNotes_faiting: Sequelize.STRING,
        dispneiaAguda: Sequelize.BOOLEAN,
        temperature: Sequelize.FLOAT,
        relatoAlergia: Sequelize.BOOLEAN,
        relatoAlergiaNotes: Sequelize.STRING,
        cefaleia: Sequelize.INTEGER,
        deficitNeurologico: Sequelize.BOOLEAN,
        traumaCranianoRecente_fainting: Sequelize.BOOLEAN,
        traumaCranianoRecenteNotes_fainting: Sequelize.STRING,
        inconsciencia_fainting: Sequelize.BOOLEAN,
        primeiraConvulsao: Sequelize.BOOLEAN,
        criseConvulsivaRecente_fainting: Sequelize.BOOLEAN,
        criseConvulsivaRecenteNotes_fainting: Sequelize.STRING,
        parestesia: Sequelize.BOOLEAN,
        parestesiaNotes: Sequelize.STRING,
        diarrhea: Sequelize.BOOLEAN,
        vomitoComSangue: Sequelize.BOOLEAN,
        vomitoComSangueNotes: Sequelize.STRING,
        dorAbdominal: Sequelize.BOOLEAN,
        alteracaoConsciencia_diarrhea: Sequelize.INTEGER,
        perfusaoPeriferica: Sequelize.INTEGER,
        temperatura_diarrhhea: Sequelize.FLOAT,
        fezesEnegrecidas: Sequelize.BOOLEAN,
        fezesEnegrecidasNotes: Sequelize.STRING,
        pain_diarrhea: Sequelize.INTEGER,
        desidratacao: Sequelize.BOOLEAN,
        desidratacaoNotes: Sequelize.STRING,
        vomitosEsparsos: Sequelize.BOOLEAN,
        eventoRecente: Sequelize.BOOLEAN,
      },
      {
        freezeTableName: true,
        underscored: true,
        tableName: 'triage-record',
        sequelize
      }
    );
  }
}

export default TriageRecord;
