import Sequelize, { Model } from 'sequelize';

class TriageRecord extends Model {
  static init(sequelize) {
    super.init(
      {
        id_patient: Sequelize.INTEGER,
        id_nurse: Sequelize.INTEGER,
        id_patient_record: Sequelize.INTEGER,
        manchesterPriority: Sequelize.INTEGER,
        mainComplain: Sequelize.STRING,
        nurseNotes: Sequelize.STRING,
        drugs: Sequelize.STRING,
        discriminators: Sequelize.STRING,
        hasAlergies: Sequelize.BOOLEAN,
        alergies: Sequelize.STRING,
        painRule: Sequelize.INTEGER,
        covid19: Sequelize.INTEGER,
        fc: Sequelize.FLOAT,
        fr: Sequelize.FLOAT,
        pas: Sequelize.FLOAT,
        pad: Sequelize.FLOAT,
        spo2: Sequelize.FLOAT,
        weight: Sequelize.FLOAT,
        headache: Sequelize.BOOLEAN,
        estadoMentalAlterado: Sequelize.BOOLEAN,
        estadoMentalAlteradoNotes: Sequelize.STRING,
        sinaisDeChoque: Sequelize.BOOLEAN,
        sinaisDeChoqueNotes: Sequelize.STRING,
        convulsion: Sequelize.BOOLEAN,
        sinaisNeurologicosFocais: Sequelize.BOOLEAN,
        sinaisNeurologicosFocaisNotes: Sequelize.STRING,
        aumentoSubitoDaDor: Sequelize.BOOLEAN,
        aumentoSubitoDaDorNotes: Sequelize.STRING,
        perdaAgudaCompletaVisao: Sequelize.BOOLEAN,
        menigismo: Sequelize.BOOLEAN,
        menigismoNotes: Sequelize.STRING,
        pain: Sequelize.INTEGER, 
        temperature: Sequelize.FLOAT,
        inconsciencia: Sequelize.BOOLEAN,
        inconscienciaNotes: Sequelize.STRING,
        diminuicaoVisao: Sequelize.BOOLEAN,
        nauseaEVomito: Sequelize.BOOLEAN,
        soreThroat: Sequelize.BOOLEAN,
        comprometimentoViasAereas: Sequelize.BOOLEAN,
        comprometimentoViasAereasNotes: Sequelize.STRING,
        pain: Sequelize.INTEGER,
        estridorLaringeo: Sequelize.BOOLEAN,
        estridorLaringeoNotes: Sequelize.STRING,
        viagemRecente: Sequelize.BOOLEAN,
        temperatura: Sequelize.FLOAT,
        dificuldadeDeglutir: Sequelize.BOOLEAN,
        ardenciaGarganta: Sequelize.BOOLEAN,
        convulsion: Sequelize.BOOLEAN,
        convulsaoAtiva: Sequelize.BOOLEAN,
        comprometimentoViasAereas: Sequelize.BOOLEAN,
        comprometimentoViasAereasNotes: Sequelize.STRING,
        alteracoesGlicemicas: Sequelize.BOOLEAN,
        alteracoesGlicemicasNumber: Sequelize.INTEGER,
        respiracaoInadequada: Sequelize.BOOLEAN,
        respiracaoInadequadaNotes: Sequelize.STRING,
        sinaisNeurologicosFocais: Sequelize.BOOLEAN,
        sinaisNeurologicosFocaisNotes: Sequelize.STRING,
        criseConvulsivaReentrante: Sequelize.BOOLEAN,
        menigismo: Sequelize.BOOLEAN,
        menigismoNotes: Sequelize.STRING,
        overdoseEnvenenamento: Sequelize.BOOLEAN,
        overdoseEnvenenamentoNotes: Sequelize.STRING,
        traumaCranianoRecente: Sequelize.BOOLEAN, 
        traumaCranianoRecenteNotes: Sequelize.STRING,
        posComicial: Sequelize.BOOLEAN,
        posComicialNotes: Sequelize.STRING,
        epilepsiaTratada: Sequelize.BOOLEAN,
        epilepsiaTratadaNotes: Sequelize.STRING,
        criseConvulsivaRecente: Sequelize.BOOLEAN,
        criseConvulsivaRecenteNotes: Sequelize.STRING,
        fainting: Sequelize.BOOLEAN,
        alteracaoConsciencia: Sequelize.INTEGER,
        comprometimentoViasAereas: Sequelize.BOOLEAN,
        comprometimentoViasAereasNotes: Sequelize.STRING,
        alteracoesGlicemicas: Sequelize.BOOLEAN,
        alteracoesGlicemicasNumber: Sequelize.INTEGER,
        rigidez: Sequelize.STRING,
        rigidezNotes: Sequelize.BOOLEAN,
        sinaisDeChoque: Sequelize.BOOLEAN,
        pulsoAnormal: Sequelize.STRING,
        dorToracica: Sequelize.BOOLEAN, 
        dorToracicaNotes: Sequelize.BOOLEAN,
        disturbioSubitoEquilibrio: Sequelize.BOOLEAN,
        disturbioSubitoEquilibrioNotes: Sequelize.STRING,
        pain: Sequelize.INTEGER,
        posComicial: Sequelize.BOOLEAN,
        posComicialNotes: Sequelize.STRING,
        dispneiaAguda: Sequelize.BOOLEAN,
        temperature: Sequelize.FLOAT,
        relatoAlergia: Sequelize.BOOLEAN,
        relatoAlergiaNotes: Sequelize.STRING,
        cefaleia: Sequelize.INTEGER,
        deficitNeurologico: Sequelize.BOOLEAN,
        traumaCranianoRecente: Sequelize.BOOLEAN,
        traumaCranianoRecenteNotes: Sequelize.STRING,
        inconsciencia: Sequelize.BOOLEAN,
        primeiraConvulsao: Sequelize.BOOLEAN,
        criseConvulsivaRecente: Sequelize.BOOLEAN,
        criseConvulsivaRecenteNotes: Sequelize.STRING,
        parestesia: Sequelize.BOOLEAN,
        parestesiaNotes: Sequelize.STRING,
        diarrhea: Sequelize.BOOLEAN,
        vomitoComSangue: Sequelize.BOOLEAN,
        vomitoComSangueNotes: Sequelize.STRING,
        dorAbdominal: Sequelize.BOOLEAN,
        alteracaoConsciencia: Sequelize.INTEGER,
        perfusaoPeriferica: Sequelize.INTEGER,
        temperatura: Sequelize.FLOAT,
        fezesEnegrecidas: Sequelize.BOOLEAN,
        fezesEnegrecidasNotes: Sequelize.STRING,
        pain: Sequelize.INTEGER,
        desidratacao: Sequelize.BOOLEAN,
        desidratacaoNotes: Sequelize.STRING,
        vomitosEsparsos: Sequelize.BOOLEAN,
        eventoRecente: Sequelize.BOOLEAN
    
      },
      {
        freezeTableName: true,
        underscored: true,
        tableName: 'triage-record',
        sequelize
      }
    );
  }
}

export default TriageRecord;
