import initialState from './initialState';
import {
  RESET_TRIAGE, HEADACHE_TRIAGE, SORETHROAT_TRIAGE, DIARRHEA_TRIAGE,
  FAINTING_TRIAGE, CONVULSION_TRIAGE
} from '../actions/types';

const triageReducer = (state = initialState.triageRecord, action) => {
  console.log(`Action: ${JSON.stringify(action)}`);

  if (action === undefined) {
    return state;
  }

  switch (action.type) {
    case HEADACHE_TRIAGE:
      return {
        ...state,
        id_patient: action.payload.id_patient,
        id_nurse: action.payload.id_nurse,
        id_patient_record: action.payload.id_patient_record,
        main_complain: action.payload.main_complain,
        nurse_notes: action.payload.nurse_notes,
        drugs: action.payload.drugs,
        discriminators: action.payload.discriminators,
        has_alergies: action.payload.has_alergies,
        alergies: action.payload.alergies,
        pain_rule: action.payload.pain_rule,
        covid19: action.payload.covid19,
        fc: action.payload.fc,
        fr: action.payload.fr,
        pas: action.payload.pas,
        pad: action.payload.pad,
        spo2: action.payload.spo2,
        weight: action.payload.weight,
        headache: action.payload.headache,
        estadomental_alterado: action.payload.estadomental_alterado,
        estado_mental_alterado_notes: action.payload.estado_mental_alterado_notes,
        sinais_de_choque_headache: action.payload.sinais_de_choque_headache,
        sinaisdechoquenotes_headache: action.payload.sinaisdechoquenotes_headache,
        convulsion_headache: action.payload.convulsion_headache,
        sinais_neurologicos_focais_headache: action.payload.sinais_neurologicos_focais_headache,
        sinais_neurologicos_focais_notes_headache: action.payload.sinais_neurologicos_focais_notes_headache,
        aumento_subitodador: action.payload.aumento_subitodador,
        aumento_subito_da_dornotes: action.payload.aumento_subito_da_dornotes,
        perda_aguda_completa_visao: action.payload.perda_aguda_completa_visao,
        menigismo_headache: action.payload.menigismo_headache,
        menigismo_notes_headache: action.payload.menigismo_notes_headache,
        pain_headache: action.payload.pain_headache,
        temperature_headache: action.payload.temperature_headache,
        inconsciencia_headache: action.payload.inconsciencia_headache,
        inconsciencia_notes_headache: action.payload.inconsciencia_notes_headache,
        diminuicao_visao: action.payload.diminuicao_visao,
        nausea_e_vomito: action.payload.nausea_e_vomito,
      };

    case SORETHROAT_TRIAGE:
      return {
        ...state,
        id_patient: action.payload.id_patient,
        id_nurse: action.payload.id_nurse,
        id_patient_record: action.payload.id_patient_record,
        main_complain: action.payload.main_complain,
        nurse_notes: action.payload.nurse_notes,
        drugs: action.payload.drugs,
        discriminators: action.payload.discriminators,
        has_alergies: action.payload.has_alergies,
        alergies: action.payload.alergies,
        pain_rule: action.payload.pain_rule,
        covid19: action.payload.covid19,
        fc: action.payload.fc,
        fr: action.payload.fr,
        pas: action.payload.pas,
        pad: action.payload.pad,
        spo2: action.payload.spo2,
        weight: action.payload.weight,
        sore_throat: action.payload.ore_throat,
        comprometimento_vias_aereas_soathroat: action.payload.comprometimento_vias_aereas_soathroat,
        comprometimento_vias_aereas_notes_soathroat: action.payload.comprometimento_vias_aereas_notes_soathroat,
        pain_soathroat: action.payload.pain_soathroat,
        estridor_laringeo: action.payload.estridor_laringeo,
        estridor_laringeo_notes: action.payload.estridor_laringeo_notes,
        viagem_recente: action.payload.viagem_recente,
        temperatura_soathroat: action.payload.temperatura_soathroat,
        dificuldade_deglutir: action.payload.dificuldade_deglutir,
        ardencia_garganta: action.payload.ardencia_garganta,

      };

    case CONVULSION_TRIAGE:
      return {
        ...state,
        id_patient: action.payload.id_patient,
        id_nurse: action.payload.id_nurse,
        id_patient_record: action.payload.id_patient_record,
        main_complain: action.payload.main_complain,
        nurse_notes: action.payload.nurse_notes,
        drugs: action.payload.drugs,
        discriminators: action.payload.discriminators,
        has_alergies: action.payload.has_alergies,
        alergies: action.payload.alergies,
        pain_rule: action.payload.pain_rule,
        covid19: action.payload.covid19,
        fc: action.payload.fc,
        fr: action.payload.fr,
        pas: action.payload.pas,
        pad: action.payload.pad,
        spo2: action.payload.spo2,
        weight: action.payload.weight,
        convulsion: action.payload.convulsion,
        convulsao_ativa: action.payload.convulsao_ativa,
        comprometimento_vias_aereas_convulsion: action.payload.comprometimento_vias_aereas_convulsion,
        comprometimento_vias_aereas_notes_convulsion: action.payload.comprometimento_vias_aereas_notes_convulsion,
        alteracoes_glicemicas_convulsion: action.payload.alteracoes_glicemicas_convulsion,
        alteracoes_glicemicas_number_convulsion: action.payload.alteracoes_glicemicas_number_convulsion,
        respiracao_inadequada: action.payload.respiracao_inadequada,
        respiracao_inadequada_notes: action.payload.respiracao_inadequada_notes,
        sinais_neurologicos_focais_convulsion: action.payload.sinais_neurologicos_focais_convulsion,
        sinais_neurologicos_focais_notes_convulsion: action.payload.sinais_neurologicos_focais_notes_convulsion,
        crise_convulsiva_reentrante: action.payload.crise_convulsiva_reentrante,
        menigismo_convulsion: action.payload.menigismo_convulsion,
        menigismo_notes_convulsion: action.payload.menigismo_notes_convulsion,
        overdose_envenenamento: action.payload.overdose_envenenamento,
        overdose_envenenamento_notes: action.payload.overdose_envenenamento_notes,
        trauma_craniano_recente_convulsion: action.payload.trauma_craniano_recente_convulsion,
        trauma_craniano_recente_notes_convulsion: action.payload.trauma_craniano_recente_notes_convulsion,
        pos_comicial_convulsion: action.payload.pos_comicial_convulsion,
        pos_comicial_notes_convulsion: action.payload.pos_comicial_notes_convulsion,
        epilepsia_tratada: action.payload.epilepsia_tratada,
        epilepsia_tratada_notes: action.payload.epilepsia_tratada_notes,
        crise_convulsiva_recente_convulsion: action.payload.crise_convulsiva_recente_convulsion,
        crise_convulsiva_recente_notes_convulsion: action.payload.crise_convulsiva_recente_notes_convulsion,            

      };

    case FAINTING_TRIAGE:
      return {
        ...state,
        id_patient: action.payload.id_patient,
        id_nurse: action.payload.id_nurse,
        id_patient_record: action.payload.id_patient_record,
        main_complain: action.payload.main_complain,
        nurse_notes: action.payload.nurse_notes,
        drugs: action.payload.drugs,
        discriminators: action.payload.discriminators,
        has_alergies: action.payload.has_alergies,
        alergies: action.payload.alergies,
        pain_rule: action.payload.pain_rule,
        covid19: action.payload.covid19,
        fc: action.payload.fc,
        fr: action.payload.fr,
        pas: action.payload.pas,
        pad: action.payload.pad,
        spo2: action.payload.spo2,
        weight: action.payload.weight,
        fainting: action.payload.fainting,
        alteracao_consciencia_fainting: action.payload.alteracao_consciencia_fainting,
        comprometimento_vias_aereas_fainting: action.payload.comprometimento_vias_aereas_fainting,
        comprometimento_vias_areas_notes_fainting: action.payload.comprometimento_vias_aereas_notes_fainting,
        alteracoes_glicemicas_fainting: action.payload.alteracoes_glicemicas_fainting,
        alteracoes_glicemicas_number_fainting: action.payload.alteracoes_glicemicas_number_fainting,
        rigidez: action.payload.rigidez,
        rigidez_notes: action.payload.rigidez_notes,
        sinais_de_choque_fainting: action.payload.sinais_de_choque_fainting,
        sinais_de_choque_notes_fainting: action.payload.sinais_de_choque_notes_fainting,
        pulso_anormal: action.payload.pulso_anormal,
        dor_toracica: action.payload.dor_toracica,
        dor_toracica_notes: action.payload.dor_toracica_notes,
        disturbio_subito_equilibrio: action.payload.disturbio_subito_equilibrio,
        disturbio_subito_equilibrio_notes: action.payload.disturbio_subito_equilibrio_notes,
        pain_fainting: action.payload.pain_fainting,
        pos_comicial_fanting: action.payload.pos_comicial_fanting,
        pos_comicial_notes_faiting: action.payload.pos_comicial_notes_faiting,
        dispneia_aguda: action.payload.dispneia_aguda,
        temperature: action.payload.temperature,
        relato_alergia: action.payload.relato_alergia,
        relato_alergia_notes: action.payload.relato_alergia_notes,
        cefaleia: action.payload.cefaleia,
        deficit_neurologico: action.payload.deficit_neurologico,
        trauma_craniano_recente_fainting: action.payload.trauma_craniano_recente_fainting,
        trauma_craniano_recente_notes_fainting: action.payload.trauma_craniano_recente_notes_fainting,
        inconsciencia_fainting: action.payload.inconsciencia_fainting,
        primeira_convulsao: action.payload.primeira_convulsao,
        crise_convulsiva_recente_fainting: action.payload.crise_convulsiva_recente_fainting,
        crise_convulsiva_recente_notes_fainting: action.payload.crise_convulsiva_recente_notes_fainting,
        parestesia: action.payload.parestesia,
        parestesia_notes: action.payload.parestesia_notes,
      };

    case DIARRHEA_TRIAGE:
      return {
        ...state,
        id_patient: action.payload.id_patient,
        id_nurse: action.payload.id_nurse,
        id_patient_record: action.payload.id_patient_record,
        main_complain: action.payload.main_complain,
        nurse_notes: action.payload.nurse_notes,
        drugs: action.payload.drugs,
        discriminators: action.payload.discriminators,
        has_alergies: action.payload.has_alergies,
        alergies: action.payload.alergies,
        pain_rule: action.payload.pain_rule,
        covid19: action.payload.covid19,
        fc: action.payload.fc,
        fr: action.payload.fr,
        pas: action.payload.pas,
        pad: action.payload.pad,
        spo2: action.payload.spo2,
        weight: action.payload.weight,
        diarrhea: action.payload.diarrhea,
        vomito_com_sangue: action.payload.vomito_com_sangue,
        vomito_com_sangue_notes: action.payload.vomito_com_sangue_notes,
        dor_abdominal: action.payload.dor_abdominal,
        alteracao_consciencia_diarrhea: action.payload.alteracao_consciencia_diarrhea,
        perfusao_periferica: action.payload.perfusao_periferica,
        temperatura_diarrhhea: action.payload.temperatura_diarrhhea,
        fezes_enegrecidas: action.payload.fezes_enegrecidas,
        fezes_enegrecidas_notes: action.payload.fezes_enegrecidas_notes,
        pain_diarrhea: action.payload.pain_diarrhea,
        desidratacao: action.payload.desidratacao,
        desidratacao_notes: action.payload.desidratacao_notes,
        vomitos_esparsos: action.payload.vomitos_esparsos,
        evento_recente: action.payload.evento_recente,
      };

    case RESET_TRIAGE:
      return {
        id_patient: 0,
        id_nurse: 0,
        id_patient_record: 0,
        main_complain: "",
        nurse_notes: "",
        drugs: "",
        discriminators: "",
        has_alergies: false,
        alergies: "",
        pain_rule: 0,
        covid19: 0,
        fc: 0.00,
        fr: 0.00,
        pas: 0.00,
        pad: 0.00,
        spo2: 0.00,
        weight: 0.00,
        headache: false,
        estadomental_alterado: false,
        estado_mental_alterado_notes: "",
        sinais_de_choque_headache: false,
        sinaisdechoquenotes_headache: "",
        convulsion_headache: false,
        sinais_neurologicos_focais_headache: false,
        sinais_neurologicos_focais_notes_headache: "",
        aumento_subitodador: false,
        aumento_subito_da_dornotes: "",
        perda_aguda_completa_visao: false,
        menigismo_headache: false,
        menigismo_notes_headache: "",
        pain_headache: 0,
        temperature_headache: 0.0,
        inconsciencia_headache: false,
        inconsciencia_notes_headache: "",
        diminuicao_visao: false,
        nausea_e_vomito: false,
        sore_throat: false,
        comprometimento_vias_aereas_soathroat: false,
        comprometimento_vias_aereas_notes_soathroat: "",
        pain_soathroat: 0,
        estridor_laringeo: false,
        estridor_laringeo_notes: "",
        viagem_recente: false,
        temperatura_soathroat: 0.0,
        dificuldade_deglutir: false,
        ardencia_garganta: false,
        convulsion: false,
        convulsao_ativa: false,
        comprometimento_vias_aereas_convulsion: false,
        comprometimento_vias_aereas_notes_convulsion: "",
        alteracoes_glicemicas_convulsion: false,
        alteracoes_glicemicas_number_convulsion: 0,
        respiracao_inadequada: false,
        respiracao_inadequada_notes: "",
        sinais_neurologicos_focais_convulsion: false,
        sinais_neurologicos_focais_notes_convulsion: "",
        crise_convulsiva_reentrante: false,
        menigismo_convulsion: false,
        menigismo_notes_convulsion: "",
        overdose_envenenamento: false,
        overdose_envenenamento_notes: "",
        trauma_craniano_recente_convulsion: false,
        trauma_craniano_recente_notes_convulsion: "",
        pos_comicial_convulsion: false,
        pos_comicial_notes_convulsion: "",
        epilepsia_tratada: false,
        epilepsia_tratada_notes: "",
        crise_convulsiva_recente_convulsion: false,
        crise_convulsiva_recente_notes_convulsion: "",
        fainting: false,
        alteracao_consciencia_fainting: 0,
        comprometimento_vias_aereas_fainting: false,
        comprometimento_vias_areas_notes_fainting: "",
        alteracoes_glicemicas_fainting: false,
        alteracoes_glicemicas_number_fainting: 0,
        rigidez: false,
        rigidez_notes: "",
        sinais_de_choque_fainting: false,
        sinais_de_choque_notes_fainting: "",
        pulso_anormal: false,
        dor_toracica: false,
        dor_toracica_notes: "",
        disturbio_subito_equilibrio: false,
        disturbio_subito_equilibrio_notes: "",
        pain_fainting: 0,
        pos_comicial_fanting: false,
        pos_comicial_notes_faiting: "",
        dispneia_aguda: false,
        temperature: 0,
        relato_alergia: false,
        relato_alergia_notes: "",
        cefaleia: 0,
        deficit_neurologico: false,
        trauma_craniano_recente_fainting: false,
        trauma_craniano_recente_notes_fainting: " ",
        inconsciencia_fainting: false,
        primeira_convulsao: false,
        crise_convulsiva_recente_fainting: false,
        crise_convulsiva_recente_notes_fainting: "",
        parestesia: false,
        parestesia_notes: "",
        diarrhea: false,
        vomito_com_sangue: false,
        vomito_com_sangue_notes: "",
        dor_abdominal: false,
        alteracao_consciencia_diarrhea: 0,
        perfusao_periferica: 0,
        temperatura_diarrhhea: 0,
        fezes_enegrecidas: false,
        fezes_enegrecidas_notes: "",
        pain_diarrhea: 0,
        desidratacao: false,
        desidratacao_notes: "",
        vomitos_esparsos: false,
        evento_recente: false

      };

    default:
      return state;
  }
};

export default triageReducer;